config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations], controllers: {
    sessions: 'devise/sessions'
  }
  
  resources 'apps'
  resources 'clients'
  resources 'dashboards', only: [:index] do 
    collection do 
      get 'admin_dashboard', as: 'admin'
    end
  end
  resources 'gigs'
  resources 'skills'

  get '/tagged', to: "apps#tagged", as: :tagged

  root 'dashboards#index'
end

app/models/app.rb
# frozen_string_literal: true

class App < ApplicationRecord
  acts_as_taggable_on :tags

  belongs_to :client, inverse_of: :apps

  delegate :name, to: :client, prefix: true
  delegate :time_period, to: :client, prefix: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord
  has_many :apps, inverse_of: :client, dependent: :destroy
  has_many :gigs, inverse_of: :client, dependent: :destroy
end

app/models/gig.rb
class Gig < ApplicationRecord
  acts_as_taggable_on :tags
  
  belongs_to :client
end

app/models/skill.rb
# frozen_string_literal: true

class Skill < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  enum role: {
    public_user: 0,
    admin: 1
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  include Pagy::Backend

  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    return admin_dashboards_path if resource.admin?

    new_user_session_path
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_app, except: [:index, :new, :create, :tagged]
  skip_before_action :authenticate_user!, only: [:show, :tagged]

  def index
    @pagy, @apps = pagy(App.all.order(created_at: :desc))
    authorize @apps
  end

  def show; end

  def new
    @app = App.new
    authorize @app
  end

  def create
    @app = App.new(app_params)
    authorize @app

    if @app.save
      redirect_to apps_path, notice: 'App created.'
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @app.update(app_params)
    redirect_to apps_path, notice: 'Update successful.'
  end

  def destroy
    @app.destroy
    redirect_to apps_path, notice: 'Delete successful.'
  end

  def tagged
    if params[:tag].present?
      @apps = App.tagged_with(params[:tag]).order(created_at: :desc)
    else
      @pagy, @apps = pagy(App.all.order(created_at: :desc))
    end
    @tag = params[:tag]
    authorize @apps
  end

  private

    def set_app
      @app = App.find(params[:id])
      authorize @app
    end

    def app_params
      params.require(:app).permit(policy(App).permitted_attributes)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, except: [:index, :new, :create]

  def index
    @pagy, @clients = pagy(Client.all.order(created_at: :desc))
    authorize @clients
  end

  def show; end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to clients_path, notice: 'Create successful'
    else
      render 'new'
    end
  end

  def edit; end

  def update
    @client.update(client_params)
    redirect_to clients_path, notice: 'Update successful'
  end

  def destroy
    @client.destroy
    redirect_to clients_path, notice: 'Delete successful'
  end

  private

    def set_client
      @client = Client.find(params[:id])
      authorize @client
    end

    def client_params
      params.require(:client).permit(policy(Client).permitted_attributes)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @apps = App.all.order(created_at: :desc)
    @gigs = Gig.all.order(created_at: :asc)
    @clients = Client.all
  end

  def admin_dashboard; end
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_gig, except: [:index, :new, :create, :tagged]
  skip_before_action :authenticate_user!, only: [:show, :tagged]

  def index
    @pagy, @gigs = pagy(Gig.all.order(created_at: :asc))
    authorize @gigs
  end

  def show; end

  def new
    @gig = Gig.new
    authorize @gig
  end

  def create
    @gig = Gig.new(gig_params)
    authorize @gig

    if @gig.save
      redirect_to gigs_path, notice: 'Gig created.'
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @gig.update(gig_params)
    redirect_to gigs_path, notice: 'Update successful.'
  end

  def destroy
    @gig.destroy
    redirect_to gigs_path, notice: 'Delete successful.'
  end

  def tagged
    if params[:tag].present?
      @gigs = Gig.tagged_with(params[:tag]).order(created_at: :desc)
    else
      @pagy, @gigs = pagy(Gig.all.order(created_at: :desc))
    end
    @tag = params[:tag]
    authorize @gigs
  end

  private

    def set_gig
      @gig = Gig.find(params[:id])
      authorize @gig
    end

    def gig_params
      params.require(:gig).permit(policy(Gig).permitted_attributes)
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, except: [:index, :new, :create]

  def index
    @pagy, @skills = pagy(Skill.all)
    authorize @skills
  end

  def show; end

  def new
    @skill = Skill.new
    authorize @skill
  end

  def create
    @skill = Skill.new(skill_params)
    authorize @skill

    if @skill.save
      redirect_to skills_path, notice: 'Skill created'
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @skill.update(skill_params)
    redirect_to skills_path, notice: 'Update successful.'
  end

  def destroy
    @skill.destroy
    redirect_to skills_path, notice: 'Delete successful'
  end

  private

    def set_skill
      @skill = Skill.find(params[:id])
      authorize @skill
    end

    def skill_params
      params.require(:skill).permit(policy(Skill).permitted_attributes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def show_header 
    if current_page?(root_path) || 
        (params[:controller] == 'apps' && params[:action] == 'show') || 
        (params[:controller] == 'apps' && params[:action] == 'tagged') ||
        (params[:controller] == 'gigs' && params[:action] == 'show') || 
        (params[:controller] == 'gigs' && params[:action] == 'tagged')

      render 'header/header'
    else 
      render 'header/admin_header'
    end
  end
end

app/helpers/apps_helper.rb
# frozen_string_literal: true

module AppsHelper
end

app/helpers/clients_helper.rb
# frozen_string_literal: true

module ClientsHelper
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true

module DashboardsHelper
  def dev_time
    distance_of_time_in_words(Time.zone.today, Date.new(2016, 3, 30))
  end

  def writer_time
    distance_of_time_in_words(Date.new(2019, 1, 1), Date.new(2005, 7, 30))
  end

  def hamburg_time
    distance_of_time_in_words(Time.zone.today, Date.new(2020, 10, 30))
  end

  def logout_link
    render 'header/logout' if current_user
  end

  def admin_dashboard_link
    return unless current_user

    link_to 'Admin Dashboard', admin_dashboards_path, class: 'nav-link'
  end

  # rubocop:disable Rails/ContentTag
  def show_card_time_period(app)
    return if app.time.blank?

    tag :div, class: 'card-footer text-muted' do
      app.time_period
    end
  end
  # rubocop:enable Rails/ContentTag
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/skills_helper.rb
# frozen_string_literal: true

module SkillsHelper
end

app/views/apps/_app.html.erb
<div id="<%= dom_id app %>">
  <div class='row'>
    <div class='col text-center'>
      <strong>Name: </strong><%= app.name %>
    </div>
    <div class='col text-center'>
      <strong>Img Url: </strong><%= app.img_url %>
    </div>
  </div>

  <div class='row'>
    <div class='col text-center'>
      <strong>Description: </strong><%= app.description %>
    </div>
    <div class='col text-center'>
      <strong>Short Description: </strong><%= app.short_description %>
    </div>
  </div>

  <div class='row'>
    <div class='col text-center'>
      <strong>Time Period: </strong><%= app.time_period %>
    </div>
    <div class='col text-center'>
      <strong>Additional Notes: </strong><%= app.additional_notes %>
    </div>
  </div>

  <div class='row'>
    <div class='col text-center'>
      <strong>Biggest Challenges: </strong><%= app.biggest_challenge %>
    </div>
  </div>
</div>

app/views/apps/_form.html.erb
<%= form_with(model: @app) do |form| %>
  <div class='container'>
    <%= render 'partials/form_errors', object: @app %>

    <div class='row mb-3'>
      <div class='col'>
        <%= form.label :name, class: 'form-label' %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>
      <div class='col'>
        <%= form.label :client_id, 'Client', class: 'form-label' %>
        <%= form.select :client_id, options_for_select(Client.all.map { |c| [c.name, c.id ] }), { prompt: true }, { class: 'form-select' } %>
      </div>
    </div>

    <div class='row mb-3'>
      <div class='col'>
        <%= form.label :description, class: 'form-label' %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>
      <div class='col'>
        <%= form.label :img_url, class: 'form-label' %>
        <%= form.text_field :img_url, class: 'form-control' %>
      </div>
    </div>

    <div class='row mb-3'>
      <div class='col'>
        <%= form.label :time_period, class: 'form-label' %>
        <%= form.text_field :time_period, class: 'form-control' %>
      </div>
      <div class='col'>
        <%= form.label :short_description, class: 'form-label' %>
        <%= form.text_field :short_description, class: 'form-control' %>
      </div>
    </div>

    <div class='row mb-3'>
      <div class='col'>
        <%= form.label :additional_notes, class: 'form-label' %>
        <%= form.text_area :additional_notes, class: 'form-control' %>
      </div>
      <div class='col'>
        <%= form.label :biggest_challenge, class: 'form-label' %>
        <%= form.text_area :biggest_challenge, class: 'form-control' %>
      </div>
    </div>

    <div class='row mb-3'>
      <div class='col'>
        <%= form.label :tag_list, 'Skills list', class: 'form-label' %>
        <%= form.text_field :tag_list, value: @app.send(:tag_list).to_s, class: 'form-control' %>
      </div>
    </div>

    <div class='row mb-3'>
      <div class='col'>
        <%= form.submit class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/apps/edit.html.erb
<div class='container'>
  <div class='page'>
    <%= render 'partials/page_title' %>
    <div class='row'>
      <div class='col text-center'>
        <%= render 'form', app: @app %>
      </div>
    </div>
  </div>
</div>

app/views/apps/index.html.erb
<div class='container'>
  <div class='page'>
    <%= render 'partials/page_title' %>

    <div class='row'>
      <div class='col'>
        <table class='table table-striped table-bordered table-hover'>
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Actions</th>
            <tr>
          </thead>
          <tbody>
            <% @apps.each do |app| %>
              <tr>
                <td><%= app.name %></td>
                <td><%= truncate(app.description) %></td>
                <td>
                  <%= link_to 'View', app_path(app) %> |
                  <%= link_to 'Edit', edit_app_path(app) %> |
                  <%= link_to 'Delete', app_path(app), data: {"turbo-method": :delete, turbo_confirm: 'You sure?'} %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class='row'>
      <div class='col text-center'>
        <%= render 'partials/pagy_menu' %>
      </div>
    </div>
  </div>
</div>

app/views/apps/new.html.erb
<div class='container'>
  <div class='page>
    <%= render 'partials/page_title' %>
    <div class='row'>
      <div class='col text-center'>
        <%= render 'form', app: @app %>
      </div>
    </div>
  </div>
</div>

app/views/apps/show.html.erb
<style type='text/css'>
  .app-parallax {
    background-image: url(<%= asset_path(@app.img_url)%>);
    opacity: 0.6;
    object-fit: cover;
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    min-height: 15rem;
    background-attachment: fixed;
  }
  @media only screen and (max-device-width: 1024px) {
    .app-parallax {
      background-attachment: scroll;
      background-size: cover;
    }
  }
</style>

<div class='jumbotron app-parallax'></div>

<div class='container'>
  <div class='row'>
    <div class='col app-title text-center'>
      <h4><%= @app.name %></h4>
      <p><%= @app.client.name %>, <%= @app.client.time_period %></p>
    </div>
  </div>
  <div class='row'>
    <div class='col'>
      <h4>Description</h4>
      <p><%= simple_format(@app.description) %></p>
    </div>
  </div>
  <div class='row'>
    <div class='col'>
      <h4>The biggest challenge</h4>
      <p><%= @app.biggest_challenge %></p>
    </div>
  </div>
  <div class='row skill-block'>
    <div class='col'>
      <h4>Skills</h4>
      <% @app.tag_list.each do |t| %>
        <%= link_to "# #{t}", tagged_path(tag: t), class: 'btn btn-sm btn-secondary mb-2 mt-2' %>
      <% end %>
    </div>
  </div>
</div>

app/views/apps/tagged.html.erb
<div class='container'>
  <div class='row'>
    <div class='col text-center'>
      <h4 class='mt-5 mb-5'>Apps using <%= @tag %></h4>
    </div>
  </div>
  <div class='row'>
    <% @apps.tagged_with(params[:tag], any: true).each do |app| %>
      <%= render 'partials/card', app: app %>
    <% end %>
  </div>
</div>

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <div class='row'>
    <div class='col text-center'>
      <strong>Name: </strong><%= client.name %>
    </div>
    <div class='col text-center'>
      <strong>Time Period: </strong><%= client.time_period %>
    </div>
  </div>
</div>

app/views/clients/_form.html.erb
<%= form_with(model: @client) do |form| %>
  <div class='container'>
    <%= render 'partials/form_errors', object: @client %>

    <div class='row mb-3'>
      <div class='col'>
        <%= form.label :name, class: 'form-label' %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>
      <div class='col'>
        <%= form.label :time_period, class: 'form-label' %>
        <%= form.text_field :time_period, class: 'form-control' %>
      </div>
    </div>

    <div class='row mb-3'>
      <div class='col'>
        <%= form.submit class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/clients/edit.html.erb
<div class='container'>
  <div class='page'>
    <%= render 'partials/page_title' %>
    <div class='row'>
      <div class='col text-center'>
        <%= render 'form', client: @client %>
      </div>
    </div>
  </div>
</div>

app/views/clients/index.html.erb
<div class='container'>
  <div class='page'>
    <%= render 'partials/page_title' %>

    <div class='row'>
      <div class='col'>
        <table class='table table-striped table-bordered table-hover'>
          <thead>
            <tr>
              <th>Name</th>
              <th>Time Period</th>
              <th>Actions</th>
            <tr>
          </thead>
          <tbody>
            <% @clients.each do |client| %>
              <tr>
                <td><%= client.name %></td>
                <td><%= client.time_period %></td>
                <td>
                  <%= link_to 'View', client_path(client) %> |
                  <%= link_to 'Edit', edit_client_path(client) %> |
                  <%= link_to 'Delete', client_path(client), data: {"turbo-method": :delete, turbo_confirm: 'You sure?'} %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  
    
  </div>
</div>

<%= render 'partials/pagy_menu' %>

app/views/clients/new.html.erb
<div class='container'>
  <div class='page'>
    <%= render 'partials/page_title' %>
    <div class='row'>
      <div class='col text-center'>
        <%= render 'form', client: @client %>
      </div>
    </div>
  </div>
</div>

app/views/clients/show.html.erb
<div class='container'>
  <div class='page'>
    <%= render 'partials/page_title' %>
    <div class='row justify-content-center'>
      <div class='col text-center'>
        <%= render @client %>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/admin_dashboard.html.erb
<div class="container-fluid">
  <div class="page mt-5">
    <div class='row'>
      <div class='col text-center'>
        <%= link_to 'Go to apps', apps_path, class: 'btn btn-secondary mb-2' %>
      </div>
    </div>
    <div class='row'>
      <div class='col text-center'>
        <%= link_to 'Go to clients', clients_path, class: 'btn btn-secondary mb-2' %>
      </div>
    </div>
    <div class='row'>
      <div class='col text-center'>
        <%= link_to 'Go to skills', skills_path, class: 'btn btn-secondary mb-2' %>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/index.html.erb
<div class='container-fluid'>
  <div class='portrait intro'>
    <div class='row'>
      <div class='col text-end'>
        <h1 id='intro-title'>Call me Jim.</h1>
        <p id='hero-story'>
          I've been a <b>Ruby on Rails</b> dev for <%= dev_time %>, and I was a writer and editor for <%= writer_time %> before that.
          My family moved to Hamburg from the US <%= hamburg_time %> ago to enjoy a better quality of life. Here's what I've been up to.
        </p>
      </div>
      <div class='col text-start'>
        <%= image_tag("boys_porch.jpg", alt: "Hi there.", size: '500x500', class: 'img-fluid') %>
      </div>
    </div>
    

  <div class='page'>
    <div class='app-block'>
      <div class='container'>
        <div class='row'>
          <div class='col text-center'>
            <h3 id='programmer' class='intro-subtitle'>As a Programmer</h3>
          </div>
        </div>
        <div class='row'>
          <% @apps.each do |app| %>
            <%= render 'partials/app_card', app: app %>
          <% end %>
        </div>
        <div class='row'>
          <div class='col text-center'>
            <h3 id='grammar' class="intro-subtitle">As a Grammar Pro</h3>
          </div>
        </div>
        <div class='row'>
          <% @gigs.each do |gig| %>
            <%= render 'partials/gig_card', gig: gig %>
          <% end %>
        </div>
        
        <div class='row'>
          <div class='col text-center'>
            <h3 id='about' class='intro-subtitle'>A Little More About Me</h3>
          </div>
        </div>
        <div class='row'>
          <div class='col text-center'>
            <p>If I had to make a list, I'd say there are three things I've taken from my education and previous career: a genuine love of fine details, the ability to abstract those details to see the greater picture, and the ability to take my ego out of any kind of rewriting process.</p>
            <p>I took quite a long path to having eight years of experience as a Ruby on Rails dev. I graduated college with a degree in poetry--I though I'd be a college professor by now. But, honestly, the world probably doesn't need another 400-page scholarly tome about Dylan Thomas.</p>
            <p>Having worked both in offices and remotely, I'm comfortable in both envrionments but prefer remote or hybrid. Most of my work has been deadline driven, which fits right in with agile methodologies, so I'm comfortable there, too. I have superior communication skills--I'm used to being the only expert of my realm in a discussion, so I have no reservations about holding a meeting with anyone about anything. I'm certainly a great team player and I like to think I'm fun to have around.</p>
            <p>My German skills aren't great under most circumstances. I've studied English extensively, Latin, Spanish and French for multiple years each. German follows none of those rules, so it's taken me a little time to get an ear for it. I'd say that at the grocery store, I'm close to fluent; if the topic is time travel or wormholes, I'm advanced intermediate (I've been watching that Netflix series Dark over and over); despite developing a love for Stromberg, I'm sad to say I'm still around A1 in an office environment.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/gigs/create.html.erb
<h1>Gigs#create</h1>
<p>Find me in app/views/gigs/create.html.erb</p>

app/views/gigs/destroy.html.erb
<h1>Gigs#destroy</h1>
<p>Find me in app/views/gigs/destroy.html.erb</p>

app/views/gigs/edit.html.erb
<h1>Gigs#edit</h1>
<p>Find me in app/views/gigs/edit.html.erb</p>

app/views/gigs/index.html.erb
<h1>Gigs#index</h1>
<p>Find me in app/views/gigs/index.html.erb</p>

app/views/gigs/new.html.erb
<h1>Gigs#new</h1>
<p>Find me in app/views/gigs/new.html.erb</p>

app/views/gigs/show.html.erb
<style type='text/css'>
  .app-parallax {
    background-image: url(<%= asset_path(@gig.img_url) if @gig.img_url%>);
    opacity: 0.6;
    object-fit: cover;
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    min-height: 15rem;
    background-attachment: fixed;
  }
  @media only screen and (max-device-width: 1024px) {
    .app-parallax {
      background-attachment: scroll;
      background-size: cover;
    }
  }
</style>

<div class='jumbotron app-parallax'></div>

<div class='container'>
  <div class='row'>
    <div class='col app-title text-center'>
      <h4><%= @gig.position %></h4>
      <p><%= @gig.client.name %>, <%= @gig.client.time_period %></p>
    </div>
  </div>
  <div class='row'>
    <div class='col'>
      <h4>Description</h4>
      <p><%= simple_format(@gig.description) %></p>
    </div>
  </div>
  <div class='row'>
    <div class='col'>
      <h4>The biggest challenge</h4>
      <p><%= @gig.biggest_challenge %></p>
    </div>
  </div>
  <div class='row skill-block'>
    <div class='col'>
      <h4>Skills</h4>
        <% if @gig.tag_list %>
          <% @gig.tag_list.each do |t| %>
            <%= link_to "# #{t}", tagged_path(tag: t), class: 'btn btn-sm btn-secondary mb-2 mt-2' %>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/gigs/update.html.erb
<h1>Gigs#update</h1>
<p>Find me in app/views/gigs/update.html.erb</p>

app/views/header/_admin_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'Back to Portfolio', root_path, class: 'navbar-brand' %>
    <%= link_to 'Back to Admin Dash', admin_dashboards_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" 
            type="button" 
            data-bs-toggle="collapse" 
            data-bs-target="#adminNavBar" 
            aria-controls="adminNavBar" 
            aria-expanded="false" 
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="adminNavBar">
      <ul class="navbar-nav ms-auto">
        <li class='nav-item dropdown'>
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Apps
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><%= link_to 'New', new_app_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'Index', apps_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
        <li class='nav-item dropdown'>
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Client
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><%= link_to 'New', new_client_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'Index', clients_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Skills
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><%= link_to 'New', new_skill_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'Index', skills_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
        <%= logout_link %>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_app_card.html.erb
<div class='col card-col'>
  <div class='card border-dark mx-auto hvr-grow-shadow text-center'>
    <div class='card-body d-flex flex-column text-dark'>
      <h5 class='card-title'><%= app.name || 'nope'%></h5>
      <p class='card-text'><%= app.short_description || 'nope' %></p>
      <%= link_to 'More', app_path(app), class: 'btn btn-outline-secondary mt-auto' %>
    </div>
    <div class="card-footer text-muted">
      <%= app.client.name %><br>
      <%= app.client.time_period %>
    </div>
  </div>
</div>

app/views/partials/_card.html.erb
<div class='col card-col'>
  <div class='card border-dark mx-auto hvr-grow-shadow text-center'>
    <div class='card-body d-flex flex-column text-dark'>
      <h5 class='card-title'><%= app.name || 'nope'%></h5>
      <p class='card-text'><%= app.short_description || 'nope' %></p>
      <%= link_to 'More', app_path(app), class: 'btn btn-outline-secondary mt-auto' %>
    </div>
    <div class="card-footer text-muted">
      <%= app.client.name %><br>
      <%= app.client.time_period %>
    </div>
  </div>
</div>

app/views/partials/_gig_card.html.erb
<div class='col card-col'>
  <div class='card border-dark mx-auto hvr-grow-shadow text-center'>
    <div class='card-body d-flex flex-column text-dark'>
      <h5 class='card-title'><%= gig.position || 'nope'%></h5>
      <p class='card-text'><%= gig.short_description || 'nope' %></p>
      <%= link_to 'More', gig_path(gig), class: 'btn btn-outline-secondary mt-auto' %>
    </div>
    <div class="card-footer text-muted">
      <%= gig.client.name %><br>
      <%= gig.client.time_period %>
    </div>
  </div>
</div>

app/views/skills/index.html.erb
<div class="container">
  <div class='page'>
    <%= render 'partials/page_title' %>

    <div class='row'>
      <div class='col'>
        <table class='table table-striped table-hover table-bordered'>
          <thead>
            <tr>
              <th>Name</th>
              <th>Actions</th>
            <tr>
          </thead>
          <tbody>
            <% @skills.each do |skill| %>
              <tr>
                <td><%= skill.name %></td>
                <td>
                  <%= link_to 'View', skill_path(skill) %> |
                  <%= link_to 'Edit', edit_skill_path(skill) %> |
                  <%= link_to 'Delete', skill_path(skill), data: {"turbo-method": :delete, turbo_confirm: 'You sure?'} %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

  
  </div>
</div>

<%= render 'partials/pagy_menu' %>